apiVersion: v1
kind: Service
metadata:
  name: quicklink
spec:
  type: NodePort
  selector:
    app: quicklink
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quicklink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quicklink
  template:
    metadata:
      labels:
        app: quicklink
    spec:
      containers:
        - name: quicklink
          image: prabhudev14/quicklink
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

